Date : 26-12-2025



In [66]:
z[:]=200
print(z)

[200 200 200 200 200 200 200 200 200 200]


In [65]:
#slicing 

#reverse 

np.flip(z)

array([15, 12,  6,  5, 11,  7, 15, 10,  6,  8], dtype=int32)

In [61]:
print(y[0,2])

10


In [59]:
y

array([[ 6,  5, 10],
       [ 6,  8,  5],
       [10, 14,  9]], dtype=int32)

In [ ]:
# indexing 



x


array([[5, 0, 0, 0, 0],
       [0, 5, 0, 0, 0],
       [0, 0, 5, 0, 0],
       [0, 0, 0, 5, 0]])

Q . give a difference between indexing and slicing 

ans : indexing accesses a single element from a sequence using a specific index, such as my_list[2], which retrieves the third item. Indexing starts from 0 for positive indices and -1 for negative ones from the end.

Slicing extracts a range of elements using start:end syntax, like my_list[1:4], creating a new subsequence


Notes----

slicing refers to the process of extracting a portion of an array or a subarray 
it allows you to access specific elements or ranges of elements in a numpy array 

indexing is the process of accessing a single element from a sequence using its position or index 

2 types of indexing :

positive : left side - 0
negative : right side - (-1)

it retrives a single elements at a specific position 

In [55]:
arr4 = arr1 - arr2
print(arr4)

arr5 = arr1 * arr2
print(arr5)

arr6 = arr1 / arr2
print(arr6)

print(arr3)


[[ 0.24010008  0.17911388 -0.67457981]
 [-0.09992184  0.30896257  0.03685443]
 [ 0.3741547   0.64037712  0.36949482]]
[[0.00105651 0.0550276  0.16601486]
 [0.07538659 0.10556014 0.00735294]
 [0.34186232 0.04740358 0.21964844]]
[[56.54674888  2.10881193  0.22124777]
 [ 0.69631907  2.50511519  1.53196566]
 [ 1.87662628 10.55615137  2.15822396]]
[[0.24874505 0.50218738 1.05788344]
 [0.55814937 0.71951264 0.17541385]
 [1.22777889 0.77440118 1.00753172]]


In [ ]:
arr1 = np.random.rand(3,3)
arr2 = np.random.rand(3,3)   

#np.add(arr1,arr2) - > by function 
arr3 = arr1 + arr2




[[0.24874505 0.50218738 1.05788344]
 [0.55814937 0.71951264 0.17541385]
 [1.22777889 0.77440118 1.00753172]]


In [41]:
print(x.mean())

1.0


In [39]:
z.argmax()

np.int64(3)

In [38]:
z.argmin()

np.int64(6)

In [37]:
z.min()

np.int32(5)

In [34]:
x.dtype

dtype('int64')

In [33]:
x.size #num of elememts

20

In [32]:
y.ndim

2

In [31]:
x.ndim

2

In [30]:
print("shape of array:", x.shape)


shape of array: (4, 5)


In [29]:
#identity matrix 

x = 5*np.eye(4,5,dtype=int)
print(x)

[[5 0 0 0 0]
 [0 5 0 0 0]
 [0 0 5 0 0]
 [0 0 0 5 0]]


In [26]:
x = np.full((5,5),7) # size and value 
x

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [24]:
x = np.ones((2,3),dtype = int)  # 2 rows and 3 columns
print(x)

[[1 1 1]
 [1 1 1]]


In [22]:
x = np.zeros((3,4),dtype = int)  # 3 rows and 4 columns
print(x)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [20]:
# 3D array 

x = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]],[[19,20,21],[22,23,24],[25,26,27]]])
print(x)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [17]:
y = np.random.randint(5,16,(3,3)) # 2D random 
print(y)

[[ 6  5 10]
 [ 6  8  5]
 [10 14  9]]


In [13]:
y = np.random.rand(3,3)
print(y)


[[0.87823076 0.81430064 0.69890763]
 [0.8068475  0.0862941  0.21056863]
 [0.15171253 0.05655655 0.21645407]]


In [12]:
# 2D array

y = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [36]:
z = np.random.randint(5,16,10) # start , last+1 , how many number
print(z)

[ 8  6 10 15  7 11  5  6 12 15]


In [10]:
x =np.random.rand(5)
print(x)

[0.82715427 0.57828551 0.85353225 0.52478642 0.43175769]


In [9]:
# 1D array 
x =np.array([1,2,3,4,5])
print(x)


[1 2 3 4 5]


Q. find a difference between python list and numpy array 

ans: Lists handle heterogeneous(mixed) data and general-purpose tasks, while NumPy arrays enforce homogeneity(same) for efficiency

In [8]:
x=np.array(l1) #numpy array
x

array([1, 2, 3, 4, 5])

In [1]:
#list 
l1 = [1,2,3,4,5]
# print(l1)
l1

[1, 2, 3, 4, 5]

numpy is package library/package . - > used for data science and ML
numpy stands for numerical python .

In [5]:
print(np.__version__)

2.3.5


In [4]:
import numpy as np

In [3]:
pip install numpy

   ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
    --------------------------------------- 0.3/12.8 MB ? eta -:--:--
   --- ------------------------------------ 1.0/12.8 MB 3.2 MB/s eta 0:00:04
   ---- ----------------------------------- 1.3/12.8 MB 3.4 MB/s eta 0:00:04
   ---- ----------------------------------- 1.6/12.8 MB 2.1 MB/s eta 0:00:06
   ----- ---------------------------------- 1.8/12.8 MB 1.7 MB/s eta 0:00:07
   ----- ---------------------------------- 1.8/12.8 MB 1.7 MB/s eta 0:00:07
   ------- -------------------------------- 2.4/12.8 MB 1.7 MB/s eta 0:00:07
   -------- ------------------------------- 2.6/12.8 MB 1.5 MB/s eta 0:00:07
   -------- ------------------------------- 2.6/12.8 MB 1.5 MB/s eta 0:00:07
   --------- ------------------------------ 2.9/12.8 MB 1.4 MB/s eta 0:00:07
   --------- ------------------------------ 3.1/12.8 MB 1.4 MB/s eta 0:00:08
   ---------- ----------------------------- 3.4/12.8 MB 1.3 MB/s eta 0:00:08
   ----------


[notice] A new release of pip is available: 24.3.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
print("hellow world!")

hellow world!


In [2]:
pip install pandas 

Note: you may need to restart the kernel to use updated packages.


Pandas 

- pandas is an open-source library for real world data analysis in python .It is built on top of Numpy.
- using pandas , data can be cleaned , transformed , manipulated , and analyzed. 
- the basic data structures of pandas are series and dataframe
  1. series object series is one dimentional labeled array .
    it supports different data types like integer , float , double etc
  2. DataFrame in pandas is a two-dimentional , tabular data structure similar to a spreadsheet or SQL table. 

it consists of row and column .

In [3]:
import pandas as pd

In [4]:
s1 = pd.Series([1, 3, 5, 7, 9])
s1

0    1
1    3
2    5
3    7
4    9
dtype: int64

In [5]:
s2 = pd.Series([10, 20, 30, 40, 50],index=['a', 'b', 'c', 'd', 'e'])
s2

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [6]:
s1.values

array([1, 3, 5, 7, 9])

In [7]:
s1.index

RangeIndex(start=0, stop=5, step=1)

In [8]:
s2.values

array([10, 20, 30, 40, 50])

In [9]:
s2.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [10]:
#Create DataFrame from list of Dict.

data = [{'Name':'Subodh','Marks':28},
        {'Name':'Amit','Marks':35},
        {'Name':'John','Marks':30},
        {'Name':'Rahul','Marks':32}]
f1=pd.DataFrame(data)
f1

Name  Marks
0  Subodh     28
1    Amit     35
2    John     30
3   Rahul     32

In [11]:
data

[{'Name': 'Subodh', 'Marks': 28},
 {'Name': 'Amit', 'Marks': 35},
 {'Name': 'John', 'Marks': 30},
 {'Name': 'Rahul', 'Marks': 32}]

In [12]:
print(f1)

     Name  Marks
0  Subodh     28
1    Amit     35
2    John     30
3   Rahul     32


In [13]:
type(f1)

pandas.core.frame.DataFrame

In [14]:
type(data)

list

In [15]:
data = pd.read_excel('Book3.xlsx')
data 

Unnamed: 0 Unnamed: 1 Unnamed: 2
0       Name     Branch   Division
1       John         CE          B
2      Priya         IT          A
3      Tannu         CE          B
4       Alex         IT          C
5    Supriya         CE          A

pip install --upgrade pip

In [16]:
Iris = pd.read_csv('Iris.csv')
Iris

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [17]:
Iris.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [18]:
Iris.tail()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica

In [19]:
Iris.index

RangeIndex(start=0, stop=150, step=1)

In [20]:
Iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


In [21]:
Iris.isna().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [22]:
cat = Iris['Species'].unique()

In [23]:
cat

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [24]:
Iris.replace("Iris-setosa","setosa",inplace=True)

In [25]:
Iris.replace("Iris-virginica","virginica",inplace=True)

In [26]:
Iris.replace("Iris-versicolor","versicolor",inplace=True)

In [27]:
cat = Iris['Species'].unique()

In [28]:
cat

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [29]:
Iris 

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm    Species
0      1            5.1           3.5            1.4           0.2     setosa
1      2            4.9           3.0            1.4           0.2     setosa
2      3            4.7           3.2            1.3           0.2     setosa
3      4            4.6           3.1            1.5           0.2     setosa
4      5            5.0           3.6            1.4           0.2     setosa
..   ...            ...           ...            ...           ...        ...
145  146            6.7           3.0            5.2           2.3  virginica
146  147            6.3           2.5            5.0           1.9  virginica
147  148            6.5           3.0            5.2           2.0  virginica
148  149            6.2           3.4            5.4           2.3  virginica
149  150            5.9           3.0            5.1           1.8  virginica

[150 rows x 6 columns]

In [30]:
Iris.describe()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [31]:
Iris[['SepalLengthCm','SepalWidthCm']].head()

SepalLengthCm  SepalWidthCm
0            5.1           3.5
1            4.9           3.0
2            4.7           3.2
3            4.6           3.1
4            5.0           3.6