Date : 26-12-2025



In [66]:
z[:]=200
print(z)

[200 200 200 200 200 200 200 200 200 200]


In [65]:
#slicing 

#reverse 

np.flip(z)

array([15, 12,  6,  5, 11,  7, 15, 10,  6,  8], dtype=int32)

In [61]:
print(y[0,2])

10


In [59]:
y

array([[ 6,  5, 10],
       [ 6,  8,  5],
       [10, 14,  9]], dtype=int32)

In [ ]:
# indexing 



x


array([[5, 0, 0, 0, 0],
       [0, 5, 0, 0, 0],
       [0, 0, 5, 0, 0],
       [0, 0, 0, 5, 0]])

Q . give a difference between indexing and slicing 

ans : indexing accesses a single element from a sequence using a specific index, such as my_list[2], which retrieves the third item. Indexing starts from 0 for positive indices and -1 for negative ones from the end.

Slicing extracts a range of elements using start:end syntax, like my_list[1:4], creating a new subsequence


Notes----

slicing refers to the process of extracting a portion of an array or a subarray 
it allows you to access specific elements or ranges of elements in a numpy array 

indexing is the process of accessing a single element from a sequence using its position or index 

2 types of indexing :

positive : left side - 0
negative : right side - (-1)

it retrives a single elements at a specific position 

In [55]:
arr4 = arr1 - arr2
print(arr4)

arr5 = arr1 * arr2
print(arr5)

arr6 = arr1 / arr2
print(arr6)

print(arr3)


[[ 0.24010008  0.17911388 -0.67457981]
 [-0.09992184  0.30896257  0.03685443]
 [ 0.3741547   0.64037712  0.36949482]]
[[0.00105651 0.0550276  0.16601486]
 [0.07538659 0.10556014 0.00735294]
 [0.34186232 0.04740358 0.21964844]]
[[56.54674888  2.10881193  0.22124777]
 [ 0.69631907  2.50511519  1.53196566]
 [ 1.87662628 10.55615137  2.15822396]]
[[0.24874505 0.50218738 1.05788344]
 [0.55814937 0.71951264 0.17541385]
 [1.22777889 0.77440118 1.00753172]]


In [ ]:
arr1 = np.random.rand(3,3)
arr2 = np.random.rand(3,3)   

#np.add(arr1,arr2) - > by function 
arr3 = arr1 + arr2




[[0.24874505 0.50218738 1.05788344]
 [0.55814937 0.71951264 0.17541385]
 [1.22777889 0.77440118 1.00753172]]


In [41]:
print(x.mean())

1.0


In [39]:
z.argmax()

np.int64(3)

In [38]:
z.argmin()

np.int64(6)

In [37]:
z.min()

np.int32(5)

In [34]:
x.dtype

dtype('int64')

In [33]:
x.size #num of elememts

20

In [32]:
y.ndim

2

In [31]:
x.ndim

2

In [30]:
print("shape of array:", x.shape)


shape of array: (4, 5)


In [29]:
#identity matrix 

x = 5*np.eye(4,5,dtype=int)
print(x)

[[5 0 0 0 0]
 [0 5 0 0 0]
 [0 0 5 0 0]
 [0 0 0 5 0]]


In [26]:
x = np.full((5,5),7) # size and value 
x

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [24]:
x = np.ones((2,3),dtype = int)  # 2 rows and 3 columns
print(x)

[[1 1 1]
 [1 1 1]]


In [22]:
x = np.zeros((3,4),dtype = int)  # 3 rows and 4 columns
print(x)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [20]:
# 3D array 

x = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]],[[19,20,21],[22,23,24],[25,26,27]]])
print(x)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [17]:
y = np.random.randint(5,16,(3,3)) # 2D random 
print(y)

[[ 6  5 10]
 [ 6  8  5]
 [10 14  9]]


In [13]:
y = np.random.rand(3,3)
print(y)


[[0.87823076 0.81430064 0.69890763]
 [0.8068475  0.0862941  0.21056863]
 [0.15171253 0.05655655 0.21645407]]


In [12]:
# 2D array

y = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [36]:
z = np.random.randint(5,16,10) # start , last+1 , how many number
print(z)

[ 8  6 10 15  7 11  5  6 12 15]


In [10]:
x =np.random.rand(5)
print(x)

[0.82715427 0.57828551 0.85353225 0.52478642 0.43175769]


In [9]:
# 1D array 
x =np.array([1,2,3,4,5])
print(x)


[1 2 3 4 5]


Q. find a difference between python list and numpy array 

ans: Lists handle heterogeneous(mixed) data and general-purpose tasks, while NumPy arrays enforce homogeneity(same) for efficiency

In [8]:
x=np.array(l1) #numpy array
x

array([1, 2, 3, 4, 5])

In [1]:
#list 
l1 = [1,2,3,4,5]
# print(l1)
l1

[1, 2, 3, 4, 5]

numpy is package library/package . - > used for data science and ML
numpy stands for numerical python .

In [5]:
print(np.__version__)

2.3.5


In [4]:
import numpy as np

In [3]:
pip install numpy

   ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
    --------------------------------------- 0.3/12.8 MB ? eta -:--:--
   --- ------------------------------------ 1.0/12.8 MB 3.2 MB/s eta 0:00:04
   ---- ----------------------------------- 1.3/12.8 MB 3.4 MB/s eta 0:00:04
   ---- ----------------------------------- 1.6/12.8 MB 2.1 MB/s eta 0:00:06
   ----- ---------------------------------- 1.8/12.8 MB 1.7 MB/s eta 0:00:07
   ----- ---------------------------------- 1.8/12.8 MB 1.7 MB/s eta 0:00:07
   ------- -------------------------------- 2.4/12.8 MB 1.7 MB/s eta 0:00:07
   -------- ------------------------------- 2.6/12.8 MB 1.5 MB/s eta 0:00:07
   -------- ------------------------------- 2.6/12.8 MB 1.5 MB/s eta 0:00:07
   --------- ------------------------------ 2.9/12.8 MB 1.4 MB/s eta 0:00:07
   --------- ------------------------------ 3.1/12.8 MB 1.4 MB/s eta 0:00:08
   ---------- ----------------------------- 3.4/12.8 MB 1.3 MB/s eta 0:00:08
   ----------


[notice] A new release of pip is available: 24.3.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
print("hellow world!")

hellow world!
