Tutorial 1: Explore Numpy Library to Analyze Data

Description: Use Numpy library for numerical data analysis.

Dataset: Randomly generated numerical data.

Task: Perform basic operations like array creation, indexing, slicing, and mathematical operations.

In [3]:
pip install numpy

   ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
    --------------------------------------- 0.3/12.8 MB ? eta -:--:--
   --- ------------------------------------ 1.0/12.8 MB 3.2 MB/s eta 0:00:04
   ---- ----------------------------------- 1.3/12.8 MB 3.4 MB/s eta 0:00:04
   ---- ----------------------------------- 1.6/12.8 MB 2.1 MB/s eta 0:00:06
   ----- ---------------------------------- 1.8/12.8 MB 1.7 MB/s eta 0:00:07
   ----- ---------------------------------- 1.8/12.8 MB 1.7 MB/s eta 0:00:07
   ------- -------------------------------- 2.4/12.8 MB 1.7 MB/s eta 0:00:07
   -------- ------------------------------- 2.6/12.8 MB 1.5 MB/s eta 0:00:07
   -------- ------------------------------- 2.6/12.8 MB 1.5 MB/s eta 0:00:07
   --------- ------------------------------ 2.9/12.8 MB 1.4 MB/s eta 0:00:07
   --------- ------------------------------ 3.1/12.8 MB 1.4 MB/s eta 0:00:08
   ---------- ----------------------------- 3.4/12.8 MB 1.3 MB/s eta 0:00:08
   ----------


[notice] A new release of pip is available: 24.3.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [5]:
print(np.__version__)

2.3.5


In [4]:
# Q.1 : Import numpy library.
import numpy as np

In [ ]:
#Q.2 : Create 1D array with 5 elements.
import numpy as np
a = np.array([1, 2, 3, 4, 5])
print(a)  

[1 2 3 4 5]


In [ ]:
#Q.3 :Create 1D array with 5 elements random value. (by default values between 0 to 1)
import numpy as np
a = np.random.rand(5)
print(a)

[0.90038046 0.68497816 0.50521539 0.14364408 0.25959105]


In [ ]:
#Q.4 : Generate random value from range 5 to 15 with 1D array size 10.
import numpy as np
a = np.random.randint(5, 15, 10)
print(a)


[ 7  6 13  9  7 13  9 11  5  5]


In [ ]:
#Q.5 : Create 2D array - 4 by 3 size
import numpy as np
a = np.zeros((4, 3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
#Q.6 : Create 2D array with size 3 by 3. Elements values are random number(by default values between 0 to 1)
import numpy as np
a = np.random.rand(3, 3)
print(a)

[[0.75090437 0.59264252 0.13410639]
 [0.57790627 0.21536684 0.27545521]
 [0.96417752 0.07961345 0.69896837]]


In [ ]:
#Q.7 : Generate random value from range 5 to 15 with 2D array size 3 by 3.
import numpy as np
a = np.random.randint(5, 15, (3, 3))
print(a)

[[ 9 10  7]
 [ 9  8 13]
 [ 9  5 13]]


In [ ]:
#Q.8 : Create 3D array with size 2 * 3 * 2.
import numpy as np
a = np.zeros((2, 3, 2))
print(a)


[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [ ]:
#Q.9 : Initialize 5 by 5 array with all values are zeros
import numpy as np
a = np.zeros((5, 5))
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
#Q.10 : Initialize 5 by 5 array with all values are ones.
import numpy as np
a = np.ones((5, 5))
print(a)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
#Q.11 : Initialize 5 by 5 array with all values are particular values(consider 4).
import numpy as np
a = np.full((5, 5), 4)
print(a)

[[4 4 4 4 4]
 [4 4 4 4 4]
 [4 4 4 4 4]
 [4 4 4 4 4]
 [4 4 4 4 4]]


In [ ]:
#Q.12 : Create indentity matrix with all diagonal values are 1 and rest all values are zeros.
import numpy as np
a = np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [46]:
#Q.13 : Find out shape of array.
import numpy as np
print(a.shape)


(5, 5)


In [45]:
#Q.14 : Find dimension of array.
import numpy as np
print(a.ndim)


2


In [47]:
#Q.15 : Find no. of elements of from above any array.
import numpy as np
print(a.size)



25


In [40]:
#Q.16 : Find type of array.
import numpy as np
print(a.dtype)


int64


In [48]:
#Q.17 : Find maximum value from array.
import numpy as np
print(a.max())


4


In [49]:
#Q.18 : Find minimum value from array.
import numpy as np
print(a.min())


4


In [50]:
#Q.19 : Find average (mean) values from array.

import numpy as np
print(a.mean())


4.0


In [51]:
#Q.20 : Find location of maximum value from array..
import numpy as np
print(np.argmax(a))


0


In [1]:
#Q.21 : Create two 2D array of size 3 by 3 and perform four basic mathematical operations.
import numpy as np

a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
b = np.array([[9,8,7],
              [6,5,4],
              [3,2,1]])

print("a:\n", a)
print("b:\n", b)

print("\na + b:\n", a + b)    # addition
print("a - b:\n", a - b)     # subtraction
print("a * b:\n", a * b)     # element-wise multiplication
print("a / b:\n", a / b) 

a:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
b:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]

a + b:
 [[10 10 10]
 [10 10 10]
 [10 10 10]]
a - b:
 [[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]
a * b:
 [[ 9 16 21]
 [24 25 24]
 [21 16  9]]
a / b:
 [[0.11111111 0.25       0.42857143]
 [0.66666667 1.         1.5       ]
 [2.33333333 4.         9.        ]]


In [ ]:
#Q.22 : Print index 2 and -2 value for 1D array. (indexing).
import numpy as np
print(a[2], a[-2])


[7 8 9] [4 5 6]


In [ ]:
#Q.23 : Perform indexing operations with 2D array.
import numpy as np
print(a[1,2])

6


In [ ]:
#Q.24 : Print value of index 2 to 5 (slicing)
import numpy as np
print(a[2:5])




[[7 8 9]]


In [ ]:
#Q.25 : Print from index 0 to 5 values
import numpy as np
print(a[:6])


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#Q.26 : Print from index 5 to all
import numpy as np
print(a[5:])

[]


In [ ]:
#Q.27 : Reassign value for particular index.
import numpy as np
a[2] = 50
print(a)


[[100 100 100]
 [100 100 100]
 [ 50  50  50]]


In [ ]:
#Q.28 : Reassign value 100 to all elements.
import numpy as np
a[:] = 100
print(a)

[[100 100 100]
 [100 100 100]
 [100 100 100]]


In [ ]:
#Q.29 : Extract elements from index 1 to 7 with a step of 2.
import numpy as np
print(a[1:7:2])

[[100 100 100]]


In [ ]:
#Q.30 : Print Reverse the array.
import numpy as np
print(a[::-1])


[[100 100 100]
 [100 100 100]
 [100 100 100]]


Tutorial : 2 - Explore Pandas library to analyze  and manipulate data.
Description: Use Pandas library for data analysis and manipulation.

Dataset: Sample CSV file

In [4]:
#Q.1 Import numpy and pandas library.

import pandas as pd 

In [14]:
#Q.2 Define series with 3 elements.

s1 = pd.Series([1, 3, 5,])
s1

0    1
1    3
2    5
dtype: int64

In [17]:
#Q.3 Define a series with a custom index.

s2 = pd.Series([10, 20, 30, 40, 50],index=['a', 'b', 'c', 'd', 'e'])
s2


a    10
b    20
c    30
d    40
e    50
dtype: int64

In [18]:
#Q.4 Fetch Series value and index.

s2.values



array([10, 20, 30, 40, 50])

In [19]:
s2.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [20]:
#Q.5 Create DataFrame from list of Dict.
data = [{'Name':'Subodh','Marks':28},
        {'Name':'Amit','Marks':35},
        {'Name':'John','Marks':30},
        {'Name':'Rahul','Marks':32}]
f1=pd.DataFrame(data)
f1

Name  Marks
0  Subodh     28
1    Amit     35
2    John     30
3   Rahul     32

In [3]:
# Q.6 Create sample excel file in your computer with columns “name”, “Branch” and “Division”. Add atleast 5 records in excel file.  Read the excel file in .ipynb.
import pandas as pd
data = pd.read_excel('Book3.xlsx')
data

Unnamed: 0 Unnamed: 1 Unnamed: 2
0       Name     Branch   Division
1       John         CE          B
2      Priya         IT          A
3      Tannu         CE          B
4       Alex         IT          C
5    Supriya         CE          A

In [22]:
#Q.7 Explore Kaggle: Your Machine Learning and Data Science Community and UCI Machine Learning Repository for a dataset. Search iris dataset and download.
#Q.8 Read iris dataset from csv file format and findout no. of rows and columns.

Iris = pd.read_csv('Iris.csv')
Iris

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [23]:
#Q.9 Perform the following operation on the iris dataset.
# a. Fetch the first 5 and last 5 rows.

Iris.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [24]:
Iris.tail()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica

In [ ]:
# b. Find index.
Iris.index


RangeIndex(start=0, stop=150, step=1)

In [ ]:
# c. Find column name and rename it with SepalLengthCm':'Sepal_Length','SepalWidthCm':'Sepal_Width','PetalLengthCm':'Petal_Length','PetalWidthCm':'Petal_Width'
Iris.rename(columns={
    'SepalLengthCm': 'Sepal_Length',
    'SepalWidthCm': 'Sepal_Width',
    'PetalLengthCm': 'Petal_Length',
    'PetalWidthCm': 'Petal_Width'
}, inplace=True)

Iris

Id  Sepal_Length  Sepal_Width  Petal_Length  Petal_Width         Species
0      1           5.1          3.5           1.4          0.2     Iris-setosa
1      2           4.9          3.0           1.4          0.2     Iris-setosa
2      3           4.7          3.2           1.3          0.2     Iris-setosa
3      4           4.6          3.1           1.5          0.2     Iris-setosa
4      5           5.0          3.6           1.4          0.2     Iris-setosa
..   ...           ...          ...           ...          ...             ...
145  146           6.7          3.0           5.2          2.3  Iris-virginica
146  147           6.3          2.5           5.0          1.9  Iris-virginica
147  148           6.5          3.0           5.2          2.0  Iris-virginica
148  149           6.2          3.4           5.4          2.3  Iris-virginica
149  150           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 6 columns]

In [ ]:
# d. replace "Iris-versicolor" with "versicolor", same way do for rest 2 categories.
Iris.replace("Iris-setosa","setosa",inplace=True)
Iris.replace("Iris-versicolor","versicolor",inplace=True)
Iris.replace("Iris-virginica","virginica",inplace=True)

Iris

Id  Sepal_Length  Sepal_Width  Petal_Length  Petal_Width    Species
0      1           5.1          3.5           1.4          0.2     setosa
1      2           4.9          3.0           1.4          0.2     setosa
2      3           4.7          3.2           1.3          0.2     setosa
3      4           4.6          3.1           1.5          0.2     setosa
4      5           5.0          3.6           1.4          0.2     setosa
..   ...           ...          ...           ...          ...        ...
145  146           6.7          3.0           5.2          2.3  virginica
146  147           6.3          2.5           5.0          1.9  virginica
147  148           6.5          3.0           5.2          2.0  virginica
148  149           6.2          3.4           5.4          2.3  virginica
149  150           5.9          3.0           5.1          1.8  virginica

[150 rows x 6 columns]

In [32]:
# e.Find Statistical description.
Iris.describe()

Id  Sepal_Length  Sepal_Width  Petal_Length  Petal_Width
count  150.000000    150.000000   150.000000    150.000000   150.000000
mean    75.500000      5.843333     3.054000      3.758667     1.198667
std     43.445368      0.828066     0.433594      1.764420     0.763161
min      1.000000      4.300000     2.000000      1.000000     0.100000
25%     38.250000      5.100000     2.800000      1.600000     0.300000
50%     75.500000      5.800000     3.000000      4.350000     1.300000
75%    112.750000      6.400000     3.300000      5.100000     1.800000
max    150.000000      7.900000     4.400000      6.900000     2.500000

In [33]:
# f. extract specific column.

Iris[['Sepal_Length']]

Sepal_Length
0             5.1
1             4.9
2             4.7
3             4.6
4             5.0
..            ...
145           6.7
146           6.3
147           6.5
148           6.2
149           5.9

[150 rows x 1 columns]

In [35]:
# g. add new column with condition.

Iris['Is_Wide'] = Iris['Sepal_Width'] > 3.0
Iris

Id  Sepal_Length  Sepal_Width  Petal_Length  Petal_Width    Species  \
0      1           5.1          3.5           1.4          0.2     setosa   
1      2           4.9          3.0           1.4          0.2     setosa   
2      3           4.7          3.2           1.3          0.2     setosa   
3      4           4.6          3.1           1.5          0.2     setosa   
4      5           5.0          3.6           1.4          0.2     setosa   
..   ...           ...          ...           ...          ...        ...   
145  146           6.7          3.0           5.2          2.3  virginica   
146  147           6.3          2.5           5.0          1.9  virginica   
147  148           6.5          3.0           5.2          2.0  virginica   
148  149           6.2          3.4           5.4          2.3  virginica   
149  150           5.9          3.0           5.1          1.8  virginica   

     Is_Wide  
0       True  
1      False  
2       True  
3       True  
4       True  
..       ...  
145    False  
146    False  
147    False  
148     True  
149    False  

[150 rows x 7 columns]

In [44]:
# h. drop added column.
Iris = Iris.drop(columns=['Is_Wide'], errors='ignore')
Iris


Id  Sepal_Length  Sepal_Width  Petal_Length  Petal_Width    Species
0      1           5.1          3.5           1.4          0.2     setosa
1      2           4.9          3.0           1.4          0.2     setosa
2      3           4.7          3.2           1.3          0.2     setosa
3      4           4.6          3.1           1.5          0.2     setosa
4      5           5.0          3.6           1.4          0.2     setosa
..   ...           ...          ...           ...          ...        ...
145  146           6.7          3.0           5.2          2.3  virginica
146  147           6.3          2.5           5.0          1.9  virginica
147  148           6.5          3.0           5.2          2.0  virginica
148  149           6.2          3.4           5.4          2.3  virginica
149  150           5.9          3.0           5.1          1.8  virginica

[150 rows x 6 columns]

In [ ]:
# 