Tutorial 1: Explore Numpy Library to Analyze Data

Description: Use Numpy library for numerical data analysis.

Dataset: Randomly generated numerical data.

Task: Perform basic operations like array creation, indexing, slicing, and mathematical operations.

In [3]:
pip install numpy

   ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
    --------------------------------------- 0.3/12.8 MB ? eta -:--:--
   --- ------------------------------------ 1.0/12.8 MB 3.2 MB/s eta 0:00:04
   ---- ----------------------------------- 1.3/12.8 MB 3.4 MB/s eta 0:00:04
   ---- ----------------------------------- 1.6/12.8 MB 2.1 MB/s eta 0:00:06
   ----- ---------------------------------- 1.8/12.8 MB 1.7 MB/s eta 0:00:07
   ----- ---------------------------------- 1.8/12.8 MB 1.7 MB/s eta 0:00:07
   ------- -------------------------------- 2.4/12.8 MB 1.7 MB/s eta 0:00:07
   -------- ------------------------------- 2.6/12.8 MB 1.5 MB/s eta 0:00:07
   -------- ------------------------------- 2.6/12.8 MB 1.5 MB/s eta 0:00:07
   --------- ------------------------------ 2.9/12.8 MB 1.4 MB/s eta 0:00:07
   --------- ------------------------------ 3.1/12.8 MB 1.4 MB/s eta 0:00:08
   ---------- ----------------------------- 3.4/12.8 MB 1.3 MB/s eta 0:00:08
   ----------


[notice] A new release of pip is available: 24.3.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [5]:
print(np.__version__)

2.3.5


In [4]:
# Q.1 : Import numpy library.
import numpy as np

In [ ]:
#Q.2 : Create 1D array with 5 elements.
import numpy as np
a = np.array([1, 2, 3, 4, 5])
print(a)  

[1 2 3 4 5]


In [ ]:
#Q.3 :Create 1D array with 5 elements random value. (by default values between 0 to 1)
import numpy as np
a = np.random.rand(5)
print(a)

[0.90038046 0.68497816 0.50521539 0.14364408 0.25959105]


In [ ]:
#Q.4 : Generate random value from range 5 to 15 with 1D array size 10.
import numpy as np
a = np.random.randint(5, 15, 10)
print(a)


[ 7  6 13  9  7 13  9 11  5  5]


In [ ]:
#Q.5 : Create 2D array - 4 by 3 size
import numpy as np
a = np.zeros((4, 3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
#Q.6 : Create 2D array with size 3 by 3. Elements values are random number(by default values between 0 to 1)
import numpy as np
a = np.random.rand(3, 3)
print(a)

[[0.75090437 0.59264252 0.13410639]
 [0.57790627 0.21536684 0.27545521]
 [0.96417752 0.07961345 0.69896837]]


In [ ]:
#Q.7 : Generate random value from range 5 to 15 with 2D array size 3 by 3.
import numpy as np
a = np.random.randint(5, 15, (3, 3))
print(a)

[[ 9 10  7]
 [ 9  8 13]
 [ 9  5 13]]


In [ ]:
#Q.8 : Create 3D array with size 2 * 3 * 2.
import numpy as np
a = np.zeros((2, 3, 2))
print(a)


[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [ ]:
#Q.9 : Initialize 5 by 5 array with all values are zeros
import numpy as np
a = np.zeros((5, 5))
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
#Q.10 : Initialize 5 by 5 array with all values are ones.
import numpy as np
a = np.ones((5, 5))
print(a)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
#Q.11 : Initialize 5 by 5 array with all values are particular values(consider 4).
import numpy as np
a = np.full((5, 5), 4)
print(a)

[[4 4 4 4 4]
 [4 4 4 4 4]
 [4 4 4 4 4]
 [4 4 4 4 4]
 [4 4 4 4 4]]


In [ ]:
#Q.12 : Create indentity matrix with all diagonal values are 1 and rest all values are zeros.
import numpy as np
a = np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [46]:
#Q.13 : Find out shape of array.
import numpy as np
print(a.shape)


(5, 5)


In [45]:
#Q.14 : Find dimension of array.
import numpy as np
print(a.ndim)


2


In [47]:
#Q.15 : Find no. of elements of from above any array.
import numpy as np
print(a.size)



25


In [40]:
#Q.16 : Find type of array.
import numpy as np
print(a.dtype)


int64


In [48]:
#Q.17 : Find maximum value from array.
import numpy as np
print(a.max())


4


In [49]:
#Q.18 : Find minimum value from array.
import numpy as np
print(a.min())


4


In [50]:
#Q.19 : Find average (mean) values from array.

import numpy as np
print(a.mean())


4.0


In [51]:
#Q.20 : Find location of maximum value from array..
import numpy as np
print(np.argmax(a))


0


In [1]:
#Q.21 : Create two 2D array of size 3 by 3 and perform four basic mathematical operations.
import numpy as np

a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
b = np.array([[9,8,7],
              [6,5,4],
              [3,2,1]])

print("a:\n", a)
print("b:\n", b)

print("\na + b:\n", a + b)    # addition
print("a - b:\n", a - b)     # subtraction
print("a * b:\n", a * b)     # element-wise multiplication
print("a / b:\n", a / b) 

a:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
b:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]

a + b:
 [[10 10 10]
 [10 10 10]
 [10 10 10]]
a - b:
 [[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]
a * b:
 [[ 9 16 21]
 [24 25 24]
 [21 16  9]]
a / b:
 [[0.11111111 0.25       0.42857143]
 [0.66666667 1.         1.5       ]
 [2.33333333 4.         9.        ]]


In [ ]:
#Q.22 : Print index 2 and -2 value for 1D array. (indexing).
import numpy as np
print(a[2], a[-2])


[7 8 9] [4 5 6]


In [ ]:
#Q.23 : Perform indexing operations with 2D array.
import numpy as np
print(a[1,2])

6


In [ ]:
#Q.24 : Print value of index 2 to 5 (slicing)
import numpy as np
print(a[2:5])




[[7 8 9]]


In [ ]:
#Q.25 : Print from index 0 to 5 values
import numpy as np
print(a[:6])


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#Q.26 : Print from index 5 to all
import numpy as np
print(a[5:])

[]


In [ ]:
#Q.27 : Reassign value for particular index.
import numpy as np
a[2] = 50
print(a)


[[100 100 100]
 [100 100 100]
 [ 50  50  50]]


In [ ]:
#Q.28 : Reassign value 100 to all elements.
import numpy as np
a[:] = 100
print(a)

[[100 100 100]
 [100 100 100]
 [100 100 100]]


In [ ]:
#Q.29 : Extract elements from index 1 to 7 with a step of 2.
import numpy as np
print(a[1:7:2])

[[100 100 100]]


In [ ]:
#Q.30 : Print Reverse the array.
import numpy as np
print(a[::-1])


[[100 100 100]
 [100 100 100]
 [100 100 100]]
